name: Run Proxy Fetch Script

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up job
        run: |
          mkdir -p .github/scripts
          mkdir -p .github/workflows/data

      - name: Execute the script
        run: |
          bash ./script.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: "Update Configs at ${{ steps.date.outputs.date }}"
          commit_options: '--no-verify --signoff'
          commit_user_name: "anon"
          commit_user_email: "anon@example.org"
